# This file serves for generating the OptaPlanner documentation website.
# For local development, see antora-playbook-author.yml.
site:
  title: Documentation
  url: https://beautifulnature.github.io/docs
  start_page: optaplanner::planner-introduction/planner-introduction.adoc
  robots: allow
  keys:
    google_analytics: "UA-39485370-1"
content:
  edit_url: "{web_url}/edit/main/{path}"
  sources:
    - url: https://github.com/beautifulnature/optaplanner-docs.git
      #- url: ../optaplanner-docs/
      # Update with every release.
      branches: [HEAD]
      start_path: /src
      #start_path: /src
ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: 
    - path: ./supplemental-ui
        contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll
runtime:
  fetch: true
